import type { NextPage } from "next";
import { css } from "@emotion/react";
import Head from "next/head";
import Image from "next/image";
import { TweetGet } from "../components/TweetGet";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter_保護犬猫</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={mainBox}>
        <h1>Twitter_保護犬猫</h1>
        <TweetGet />
      </main>
    </div>
  );
};

export default Home;

const mainBox = css`
  h1 {
    color: #1da1f2;
    text-align: center;
  }
`;
