import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { TweetGet } from "../components/TweetGet";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Twitter</h2>
        <TweetGet />
      </main>
    </div>
  );
};

export default Home;
